name: r-cecelia-gui-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - python-dateutil
  - pytz
  - openjdk
  - pip
  - pip:
    - jupyter
    - napari[all]
    - napari-animation
    - apoc
    - napari-accelerated-pixel-and-object-classification
    - h5py
    - scikit-image
    - scanpy
    - zarr
    - dask
    - anndata
    - tifffile
    - shapely
    - pip
    - pyopencl
    - pandas
    - trimesh
    - ome-types
