services:
  app:
    build: ccia
    # image: schienstockd/cecelia:latest
    ports:
      - "0.0.0.0:6860:6860"
    expose:
      - 6860
    volumes:
      - ~/.ssh:/cecelia/.ssh:ro
      - ./datashare:/home/shiny/local
      - /Volumes/USER_data/Dominik/CECELIA_DOCKER/projects/:/cecelia/projects
      - /Volumes/USER_data/Communal/:/cecelia/data
      #- /Volumes/Lab-Mueller/:/cecelia/lab
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TERM=linux
      - JUPYTER_LIB_DIR=$JUPYTER_LIB_DIR
