version: "3.9"
services:

  app:
    build: shiny
    ports:
      - "6860:6860"
    volumes:
      - ~/.ssh:/cecelia/.ssh:ro
      - ./cecelia:/home/shiny/cecelia
      - /Volumes/Analysis_SSD/Dominik/cecelia/docker-projects/:/cecelia/projects
      - /Volumes/USER_data/Dominik/:/cecelia/data
      #- /Volumes/Lab-Mueller/:/cecelia/lab
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TERM=linux
